INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('red', 'rot', 'adj', 'Color', 'Farbe', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('green', 'gruen', 'adj', 'Color', 'Farbe', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('blue', 'blau', 'adj', 'Color', 'Farbe', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `hint1`, `hint2`, `fragePos`) VALUES ('Hello', 'Hallo', 'Greeting', 'Begruessung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('table', 'Tisch', 'n', 'Furniture', 'Moebel', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('chair', 'Stuhl', 'n', 'Furniture', 'Moebel', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('lamp', 'Lampe', 'n', 'Furnuture', 'Moebel', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('carpet', 'Teppich', 'n', 'Furnuture', 'Moebel', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('car', 'Auto', 'n', 'Vehicle', 'Fahrzeug', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('bus', 'Bus', 'n', 'Vehicle', 'Fahrzeug', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('eat', 'essen', 'v', 'food', 'Nahrung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('meat', 'Fleisch', 'n', 'food', 'Nahrung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('milk', 'Milch', 'n', 'food', 'Nahrung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('water', 'Wasser', 'n', 'food', 'Nahrung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('bread', 'Brot', 'n', 'food', 'Nahrung', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('bird', 'Vogel', 'n', 'animal', 'Tier', '1');
INSERT INTO `englischdb`.`tfrage` (`wort1`, `wort2`, `wortArt`, `hint1`, `hint2`, `fragePos`) VALUES ('dog', 'Hund', 'n', 'animal', 'Tier', '1');

UPDATE `englischdb`.`tfrage` SET `fragePos`='3' WHERE `id`='1';
UPDATE `englischdb`.`tfrage` SET `fragePos`='2' WHERE `id`='2';
UPDATE `englischdb`.`tfrage` SET `fragePos`='5' WHERE `id`='5';
UPDATE `englischdb`.`tfrage` SET `fragePos`='5' WHERE `id`='6';
UPDATE `englischdb`.`tfrage` SET `fragePos`='4' WHERE `id`='7';
UPDATE `englischdb`.`tfrage` SET `fragePos`='2' WHERE `id`='8';
UPDATE `englischdb`.`tfrage` SET `fragePos`='4' WHERE `id`='9';
UPDATE `englischdb`.`tfrage` SET `fragePos`='3' WHERE `id`='10';
UPDATE `englischdb`.`tfrage` SET `fragePos`='3' WHERE `id`='11';
UPDATE `englischdb`.`tfrage` SET `fragePos`='2' WHERE `id`='13';
UPDATE `englischdb`.`tfrage` SET `fragePos`='4' WHERE `id`='14';
UPDATE `englischdb`.`tfrage` SET `fragePos`='5' WHERE `id`='15';
UPDATE `englischdb`.`tfrage` SET `fragePos`='2' WHERE `id`='16';